name: fl_dio
description: Extended dio and added three interceptors and the JsonParse component.
version: 0.1.0
repository: https://github.com/Wayaer/fl_dio

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.2
  http_parser: ^4.0.2

dev_dependencies:
  flutter_lints: ^2.0.3
