name: fl_dio
description: A new Flutter project.
version: 0.0.1
repository: https://github.com/Wayaer/flutter_waya

environment:
  sdk: '>=3.1.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # 网络请求
  dio: ^5.3.2
  # HTTP相关处理
  http_parser: ^4.0.2

dev_dependencies:
  flutter_lints: ^2.0.3
