name: fl_dio
description: Extended dio and added three interceptors and the JsonParse component.
version: 1.2.2
repository: https://github.com/Wayaer/fl_dio

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  http_parser: ^4.0.2

dev_dependencies:
  flutter_lints: ^5.0.0
